### ISSUE TITLE
http://playnext.herokuapp.com running in Dev Mode

### ISSUE THREAD

**Issue by ScionOfBytes** [kyle-n/playnext#1]
Hi, came across your awesome site, recently. I noticed it's running rather slow and seems to be because it's running in dev mode. What do you think about putting it in production mode and enabled compression? Would boost speeds significantly.

**Comment by kyle-n** [comment]
It was, thank you for noticing! I've updated the post install scripts so it now runs in production mode. 

Also, glad you like the site! Heroku's free tier has no metrics, so I did not realize anyone was using it. :)
